[FE] 회원가입~카메라 화면 변경
kookmin-sw/capstone-2023-08 pull request #103
Opened 2023-04-28 15:07 UTC by lucyya99

카메라 안되는 걸 오늘 발견해서 조금 늦은것같아요 화면 UI 이상한점이나 바꿀점 있으면 언제든지 알려주세요! 카메라 안에 들어가는 사람 실루엣은 포토샵으로 제작해서 넣을 예정입니다!
동작화면은 9주차 회의록 노션에 있습니다. gif 넣으려고 했더니 용량이 커서 불가능하네요

## 회원가입~로그인 남은 To-do
- [ ] 카메라 실루엣 포토샵으로 제작
- [ ] 회원가입 시 id 중복체크
- [ ] 회원가입 시 id, pw 특수문자 제외 (ex. +, = 못들어가도록 설정)
- [ ] 회원가입 시 닉네임 길이 제한 (10자이내)
- [ ] 카운트 다운 10 셀 때 처음부터 원이 다 채워지도록 변경
- [ ] 회원가입 overflow (login 방식으로 해결)
- [ ] login textfield 변경 및 사용성 높이는 작업, 회원가입 버튼 변경
- [ ] login textfield id, pw 둘 중 하나라도 null이면 버튼 비활성화
- [ ] 회원가입 실패처리
- [ ] 카메라 가이드라인 안내문구 카메라 내 재표시

2023-04-28 15:32 UTC, wynter122 commented
노션 확인했어요... 진짜 괜찮은데요....? 

1. 카메라 실루엣은 지금도 저는 충분한 것 같은데, 이게 머리통 ~ 무릎 위 까지 나와야 아마 모델이 더 잘 동작하는걸로 알고있어서 그거에 맞춰서만 가이드라인을 제작하면 될거같아요. 정확한건 @dh5473 님이 알려주세요!

2. id 중복체크는 백단에서 처리가 이미 되고있어요. 이미 존재하는 id 라는 메세지를 반환중입니다. 해당 메세지만 띄우면 될것같아요.

나머지는 프론트단에서 처리해야 할 것 같네요. 추가적인 이슈 생성해서 트래킹하면 될 듯 합니다

2023-04-28 15:42 UTC, lucyya99 commented
중복체크는 프론트단에서 안해서 진행하려고 넣었습니다 👍 가이드라인은 알려주시면 참고해볼게요!

2023-05-03 14:29 UTC, wynter122 approved these changes
기능 흐름상으로는 좋습니다 코드부분은 @grapefruit224 께서 꼼꼼히 봐주세요!

2023-05-04 12:03 UTC, wynter122 requested changes

2023-05-04 12:03 UTC, wynter122 commented on client/lib/screen/camera_result.dart
> +          data: <String, String>{'user_id': userId},
get presigned url 을 할 때 파라미터가 user_id 만 들어가고 있는건가요?

2023-05-04 12:46 UTC, lucyya99 commented on client/lib/screen/camera_result.dart
> +          data: <String, String>{'user_id': userId},
get signed url 바뀌기 전에 pr 요청 보낸거라  이렇게 되어있는것같아요 수정한거에는 제대로 들어가있어요..!

2023-05-06 13:34 UTC, lucyya99 commented on client/lib/screen/camera_result.dart
> +          data: <String, String>{'user_id': userId},
#104 에서 진행 완료된 사항을 함께 추가하면서 PR에 포함되었습니다 확인해보시면 될 것 같아요

2023-05-06 16:23 UTC, grapefruit224 approved these changes
완전 수고 많으셨어여!!

2023-05-07 04:22 UTC, wynter122 approved these changes

2023-05-09 08:10 UTC, merged